### ISSUE TITLE
Read sticky trap data

### ISSUE THREAD

**Issue by rvosa** [naturalis/imgpheno#8]
- [x] represent image data internally
- [x] detect trap rectangles
- [x] normalize dimensions
- [x] reconcile different trap dimensions

**Comment by rl-michels** [comment]
In order to find the rectangles and to transform the images towards standard dimensions, it might be easiest to find the corners of the sticky trap using one of several methods within OpenCV, and then to use those corners to specify a perspective transformation. problems might arise if the bugs are also detected as corners however.

**Comment by rl-michels** [comment]
I have been able to to use a combination of techniques to find the 4 corners, order them using geometric properties of rectangles and apply a perspective change succesfully. The traps that will be used in the fieldwork in april have uniform dimensions of 198 by 147 mm, we therefore do not need to reconcile different dimensions.
